apiVersion: v1
kind: Secret
metadata:
  labels:
    app: artifactory
    chart: artifactory-11.7.6
    heritage: Tiller
    release: null
  name: -artifactory-access-config
stringData:
  access.config.patch.yml: "security:\n  tls: false\n"
type: Opaque
