apiVersion: v1
data: null
kind: Secret
metadata:
  labels:
    app: artifactory
    chart: artifactory-11.7.6
    heritage: Tiller
    release: artifactory
  name: artifactory-artifactory
type: Opaque
