# Sources:
# https://github.com/kapicorp/kapitan/blob/master/docs/compile.md#helm
# https://artifacthub.io/packages/helm/jfrog/artifactory

classes:
  - common

parameters:
  target_name: artifactory

  artifactory:
    chart_name: artifactory
    chart_version: 11.7.6
    namespace: artifactory

  kapitan:
    dependencies:
    - type: helm
      output_path: components/charts/artifactory
      source: https://charts.jfrog.io/
      version: ${artifactory:chart_version}
      chart_name: ${artifactory:chart_name}

    compile:
    - input_type: helm
      input_paths:
        - components/charts/artifactory
      output_path: .
      helm:
        params:
          namespace: ${artifactory:namespace}
          release_name: ${artifactory:chart_name}
        values:
          name: artifactory
          artifactory:
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 2
                memory: 4Gi
            javaOpts:
              xms: 1g
              xmx: 4g
          nginx:
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                cpu: 250m
                memory: 500Mi
