apiVersion: v1
data:
  postgresql-password: bFQxUm9Qb1AwaA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: artifactory
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.3.4
  name: artifactory-postgresql
type: Opaque
