apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: null
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.3.4
  name: -postgresql-headless
spec:
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: null
    app.kubernetes.io/name: postgresql
  type: ClusterIP
